# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.
# 
ARG BASE_IMAGE="ubuntu@sha256:646942475da61b4ce9cc5b3fadb42642ea90e5d0de46111458e100ff2c7031e6"
FROM $BASE_IMAGE

#
# Build container to test openenclave sdk packages
# 
RUN apt-get update \
        && apt-get install -y wget vim gnupg2 

# Add intel and microsoft ppas
RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main' > /etc/apt/sources.list.d/intel-sgx.list 
RUN echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" > /etc/apt/sources.list.d/llvm-toolchain-bionic-7.list 
RUN echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" > /etc/apt/sources.list.d/msprod.list 
RUN wget -qO - https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key >/tmp/intel-key 
RUN wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key >/tmp/llvm-key 
RUN wget -qO - https://packages.microsoft.com/keys/microsoft.asc >/tmp/micro-key 
RUN apt-key add /tmp/intel-key 
RUN apt-key add /tmp/llvm-key
RUN apt-key add /tmp/micro-key

RUN apt-get update \
        && apt-get install -y curl python3 perl git cmake clang-7 libssl-dev gdb libsgx-enclave-common libprotobuf10 libsgx-dcap-ql libsgx-dcap-ql-dev az-dcap-client 

#
# We allow overriding these settings, but if one does, the build user and id must match or else the .deb tars won't have 
# a reproducible signature, since tar entries include user and group ownerships.
ARG BUILD_USER=azureuser
ARG BUILD_USER_ID=1000
ARG BUILD_USER_HOME=/home/azureuser

