FROM scratch

# The way to get a trusted build is to start with a trusted build. If we don't have one,
# we need to use untrusted components to perform the build, then rebuild with the provisionally trusted components, 
# then compare. If we get different contents, we don't know where the problem is, but we would know there is a problem.

# this can't come from a URL because it won't get unpacked. 
# We need a tight secure CDN to hold golden images. 
ADD ubuntu-base-18.04.3-base-amd64.tar.gz  /
ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-enclave-common-dev_2.7.100.4-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=nJWY1Q%2FXHkdKRBtfKdjHEbhDZU8zTOZ6Mc0JTjZK2gU%3D /tmp/libsgx-enclave-common-dev+2.7.100.4-bionic_amd64.deb
ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-enclave-common_2.7.100.4-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=nJWY1Q%2FXHkdKRBtfKdjHEbhDZU8zTOZ6Mc0JTjZK2gU%3D /tmp/libsgx-enclave-common+2.7.100.4-bionic_amd64.deb
ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-dcap-ql-dev_1.3.101.3-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=nJWY1Q%2FXHkdKRBtfKdjHEbhDZU8zTOZ6Mc0JTjZK2gU%3D /tmp/libsgx-dcap-ql-dev_1.3.101.3-bionic1_amd64.deb
ADD https://oedownload.blob.core.windows.net/oe-build/intel-sgx/libsgx-dcap-ql_1.3.101.3-bionic1_amd64.deb?st=2019-10-25T16%3A55%3A41Z&se=2020-10-26T16%3A55%3A00Z&sp=rl&sv=2018-03-28&sr=c&sig=nJWY1Q%2FXHkdKRBtfKdjHEbhDZU8zTOZ6Mc0JTjZK2gU%3D /tmp/libsgx-dcap-ql_1.3.101.3-bionic1_amd64.deb
ADD  https://oebuildinfo.blob.core.windows.net/buildinfo/ubuntu-base-18.04.3-base-amd64.tar.gz.sig?st=2019-12-31T17%3A31%3A32Z&se=2020-01-01T17%3A31%3A32Z&sp=rl&sv=2018-03-28&sr=b&sig=QzfJ9g%2FLgL3o38I89Gn3Ecyktrm30vW8SmikPiOTkpE%3D /tmp/ubuntu-base-18.04.3-base-amd64.tar.gz.sig

#
# Check the signature.
ADD build_packages.sh /tmp

# We will run the image with build_packages.sh to generate the packages tar and sha256sum

CMD ["/bin/bash"]

