#!/usr/local/bin/python3.9
from BuildInfo import BuildInfo
import pdb
import os

if __name__ == "__main__":
    f = open("/build/secure-build.buildinfo", "r")
    buf = f.readlines()

    info = BuildInfo.from_str(buf)
    if not info.verify("/usr/local", "/usr/local"):
        print("build not verified")
        return 5
    else:
        print("build is verified")
        return 0

