#!/usr/local/bin/python3.9
from BuildInfo import BuildInfo
import pdb

try:
    __BuildInfo_Path__ = os.environ['SECUREBUILD_BUILDINFO_FILEPATH']
except KeyError:
    __BuildInfo_Path__ = '/output/secure-build.buildinfo'

if not __BuildInfo_Path__:
    __BuildInfo_Path__ = '/output/secure-build.buildinfo'

if __name__ == "__main__":
    f = open(__BuildInfo_Path__, "r")
    buf = f.readlines()

    info = BuildInfo.from_str(buf)


