#!/usr/local/bin/python3.9
from BuildInfo import BuildInfo
import pdb
import os

__Buildinfo_Path__ = os.environ['SECUREBUILD_BUILDINFO_FILEPATH']
if not __Buildinfo_Path__:
    __Buildinfo_Path__ = '/output/secure-build.buildinfo'

if __name__ == "__main__":
    f = open(__Buildinfo_Path__, "r")
    buf = f.readlines()

    info = BuildInfo.from_str(buf)
    if not info.verify(os.environ['PATH'], os.environ['LD_LIBRARY_PATH']):
        print("build not verified")
        pdb.set_trace()
    else:
        print("build is verified")
        return 0

