#!/usr/local/bin/python3.9
from BuildInfo import BuildInfo
import pdb

if __name__ == "__main__":
    f = open("/build/secure-build.buildinfo", "r")
    buf = f.readlines()

    info = BuildInfo.from_str(buf)
    info.verify(os.environ['PATH'], os.environ['LD_LIBRARY_PATH'])

    pdb.set_trace()

